#!/bin/bash

DOCKER_EXEC_FLAGS="i"

# Determine whether stdout is on a terminal
if [ -t 1 ] ; then
    DOCKER_EXEC_FLAGS+="t"
fi

#docker exec -$DOCKER_EXEC_FLAGS pmon sensors "$@"

if [ -r /usr/local/bin/platform_sensors.py ]; then
        python /usr/local/bin/platform_sensors.py
fi

